// Mock product catalog for Farm2Home marketplace
// Used as fallback when Supabase has no listings yet

import { Product } from "@/lib/data";

export const MOCK_FARMERS = [
  { id: "f1", name: "Ravi Kumar", location: "Guntur, Andhra Pradesh", distance: 12, rating: 4.8, avatar: "👨‍🌾", crops: 5, verified: true },
  { id: "f2", name: "Sunita Devi", location: "Warangal, Telangana", distance: 8, rating: 4.9, avatar: "👩‍🌾", crops: 4, verified: true },
  { id: "f3", name: "Mohan Rao", location: "Krishna, Andhra Pradesh", distance: 20, rating: 4.7, avatar: "👨‍🌾", crops: 6, verified: true },
  { id: "f4", name: "Lakshmi Bai", location: "Nellore, Andhra Pradesh", distance: 35, rating: 4.6, avatar: "👩‍🌾", crops: 3, verified: true },
  { id: "f5", name: "Venkat Reddy", location: "Karimnagar, Telangana", distance: 15, rating: 4.9, avatar: "👨‍🌾", crops: 7, verified: true },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-1",
    name: "Fresh Tomatoes",
    category: "vegetables",
    price: 28,
    marketPrice: 45,
    unit: "kg",
    quantity: 500,
    farmer: MOCK_FARMERS[0],
    image: "🍅",
    organic: true,
    rating: 4.8,
    reviews: 124,
    description: "Juicy, vine-ripened tomatoes harvested fresh from the farm. Perfect for curries, salads, and sauces.",
  },
  {
    id: "mock-2",
    name: "Potatoes",
    category: "vegetables",
    price: 22,
    marketPrice: 35,
    unit: "kg",
    quantity: 1000,
    farmer: MOCK_FARMERS[1],
    image: "🥔",
    organic: false,
    rating: 4.7,
    reviews: 89,
    description: "Premium quality potatoes, freshly dug. Ideal for frying, boiling, or making aloo sabzi.",
  },
  {
    id: "mock-3",
    name: "Red Onions",
    category: "vegetables",
    price: 32,
    marketPrice: 50,
    unit: "kg",
    quantity: 800,
    farmer: MOCK_FARMERS[2],
    image: "🧅",
    organic: false,
    rating: 4.6,
    reviews: 67,
    description: "Crisp, pungent red onions – a kitchen staple. Locally grown with no pesticide residues.",
  },
  {
    id: "mock-4",
    name: "Carrots",
    category: "vegetables",
    price: 35,
    marketPrice: 55,
    unit: "kg",
    quantity: 300,
    farmer: MOCK_FARMERS[3],
    image: "🥕",
    organic: true,
    rating: 4.9,
    reviews: 142,
    description: "Sweet and crunchy organic carrots. Great for juicing, halwa, or eating raw.",
  },
  {
    id: "mock-5",
    name: "Brinjal (Eggplant)",
    category: "vegetables",
    price: 30,
    marketPrice: 48,
    unit: "kg",
    quantity: 250,
    farmer: MOCK_FARMERS[4],
    image: "🍆",
    organic: false,
    rating: 4.5,
    reviews: 53,
    description: "Fresh, glossy brinjals harvested at peak ripeness. Perfect for Baingan Bharta.",
  },
  {
    id: "mock-6",
    name: "Basmati Rice",
    category: "grains",
    price: 85,
    marketPrice: 130,
    unit: "kg",
    quantity: 2000,
    farmer: MOCK_FARMERS[0],
    image: "🌾",
    organic: true,
    rating: 4.9,
    reviews: 211,
    description: "Aromatic organic Basmati rice from the fertile Krishna delta. Long-grain, non-sticky.",
  },
  {
    id: "mock-7",
    name: "Wheat",
    category: "grains",
    price: 30,
    marketPrice: 46,
    unit: "kg",
    quantity: 5000,
    farmer: MOCK_FARMERS[1],
    image: "🌾",
    organic: false,
    rating: 4.7,
    reviews: 98,
    description: "Hard red wheat, perfect for making atta. Stone-ground quality, free from adulterants.",
  },
  {
    id: "mock-8",
    name: "Maize (Corn)",
    category: "grains",
    price: 18,
    marketPrice: 30,
    unit: "kg",
    quantity: 3000,
    farmer: MOCK_FARMERS[2],
    image: "🌽",
    organic: false,
    rating: 4.6,
    reviews: 76,
    description: "Fresh maize cobs and dried corn. Excellent for making makki ki roti, popcorn, or cattle feed.",
  },
  {
    id: "mock-9",
    name: "Green Chillies",
    category: "spices",
    price: 60,
    marketPrice: 95,
    unit: "kg",
    quantity: 150,
    farmer: MOCK_FARMERS[3],
    image: "🌶️",
    organic: true,
    rating: 4.8,
    reviews: 163,
    description: "Fiery green chillies from Guntur – India's spice capital. Fresh, pungent, and full of flavour.",
  },
  {
    id: "mock-10",
    name: "Spinach (Palak)",
    category: "vegetables",
    price: 20,
    marketPrice: 34,
    unit: "bunch",
    quantity: 400,
    farmer: MOCK_FARMERS[4],
    image: "🥬",
    organic: true,
    rating: 4.7,
    reviews: 87,
    description: "Tender organic spinach leaves. Rich in iron and vitamins. Harvested fresh every morning.",
  },
];
